What will the following code print when compiled and run:

d2 val =

d2 val = default

d2 val = D1//true

Exception at run time.

Explanation
This is quite straight forward question. You are creating only one Data object.
You are setting its strVal field to "D1". Next, you declare another
Data variable d2 and assign to it the same Data object.

Thus, when you access strVal using d2, you will get D1.

The "throws Exception" part is not required and is there just to confuse you.
